### 0.회원가입 - ADMIN
POST http://13.124.233.97:8080/api/user/signup
Content-Type: application/json

{
  "email":"jungmin@test.com",
  "password":"@Qkrwjdals96",
  "password2": "@Qkrwjdals96",
  "username": "jungmin",
  "address" : "111-400",
  "phoneNumber": "010-1111-1111"
}

### 1.로그인후 토큰 받기
POST http://13.124.233.97:8080/api/user/signin
Content-Type: application/json

{
  "username":"jungmin",
  "password":"@Qkrwjdals96"
}