### 1.로그인후 토큰 받기
POST http://13.124.233.97:8080/api/user/signin
Content-Type: application/json

{
  "username":"jungmin",
  "password":"@Qkrwjdals96"
}
> {%
    client.global.set("access_token", response.headers.valueOf("Authorization"));
    client.log(client.global.get("access_token"));
%}


### 1. 경기장 생성
POST http://13.124.233.97:8080/api/stadiums
Content-Type: application/json
Authorization: {{access_token}}

{
  "stadiumName": "인천 문학경기장"
}

### 1. 경기장 생성 - EC2
POST https://13.124.233.97:8080/api/stadiums
Content-Type: application/json
Authorization: {{access_token}}

{
  "stadiumName": "인천 문학경기장151"
}