### 1.로그인후 토큰 받기
POST http://localhost:8080/api/user/signin
Content-Type: application/json

{
  "username":"jungmin",
  "password":"@Qkrwjdals96"
}
> {%
    client.global.set("access_token", response.headers.valueOf("Authorization"));
    client.log(client.global.get("access_token"));
%}


### 1. 경기장 생성
POST http://localhost:8080/api/stadiums
Content-Type: application/json
Authorization: {{access_token}}

{
  "stadiumName": "인천 문학경기장"
}

### 1. 경기장 생성 - EC2
POST https://yetiyt.shop/api/stadiums
Content-Type: application/json
Authorization: {{access_token}}

{
  "stadiumName": "인천 문학경기장151"
}


### 2. 경기장 조회
GET http://localhost:8080/api/stadiums/1
Content-Type: application/json
Authorization: {{access_token}}

### 3. 경기장 수정
PUT http://localhost:8080/api/stadiums/1
Content-Type: application/json
Authorization: {{access_token}}

{
  "stadiumName": "인천축구전용경기장"

}

### 4. 경기장 삭제
DELETE http://localhost:8080/api/stadiums/1
Content-Type: application/json
Authorization: {{access_token}}
