### 1.로그인후 토큰 받기
POST http://localhost:8080/api/signin
Content-Type: application/json

{
  "email":"admin@test.com",
  "password":"1234"
}
> {%
    client.global.set("access_token", response.headers.valueOf("Authorization"));
    client.log(client.global.get("access_token"));
%}

### 1. 경기장 생성
POST http://localhost:8080/api/stadiums
Content-Type: application/json
Authorization: {{access_token}}

{
  "stadiumId": 1,
  "sportName" : "2023 K-리그 한국 vs 싱가포르",
  "matchDate" : "2023-12-12"
}