### 1.로그인후 토큰 받기
POST http://localhost:8080/api/signin
Content-Type: application/json

{
  "email":"admin@test.com",
  "password":"1234"
}
> {%
    client.global.set("access_token", response.headers.valueOf("Authorization"));
    client.log(client.global.get("access_token"));
%}


### 1. 경기장 생성
POST http://localhost:8080/api/stadiums
Content-Type: application/json
Authorization: {{access_token}}

{
  "stadiumName": "잠실 체육 경기장"
}